name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Deploy
      run: |
        ARGS=""
        REF=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ "$REF" == "master" ] && ARGS="--prod"
        now $ARGS --no-clipboard --token ${{ secrets.NOW_TOKEN }}
